import SwiftUI

/// In-app icon chooser. Each option pairs an alternate-icon name (nil = the
/// primary icon) with a preview image set; both are generated by
/// Scripts/generate_icon.swift and must stay in sync with
/// ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES in project.yml.
struct AppIconPicker: View {
    struct IconOption: Identifiable {
        let label: String
        /// Name passed to `setAlternateIconName`; nil selects the primary icon.
        let iconName: String?
        let previewName: String
        var id: String { previewName }
    }

    static let options: [IconOption] = [
        IconOption(label: "Indigo", iconName: nil, previewName: "IconPreview-Indigo"),
        IconOption(label: "Ember", iconName: "AppIcon-Ember", previewName: "IconPreview-Ember"),
        IconOption(label: "Forest", iconName: "AppIcon-Forest", previewName: "IconPreview-Forest"),
        IconOption(label: "Midnight", iconName: "AppIcon-Midnight", previewName: "IconPreview-Midnight"),
        IconOption(label: "Ivory", iconName: "AppIcon-Ivory", previewName: "IconPreview-Ivory"),
    ]

    // The system persists the selection; this mirrors it for the checkmark.
    @State private var selection: String? = UIApplication.shared.alternateIconName
    @State private var errorMessage: String?

    var body: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 16) {
                ForEach(Self.options) { option in
                    Button {
                        select(option)
                    } label: {
                        VStack(spacing: 6) {
                            Image(option.previewName)
                                .resizable()
                                .frame(width: 64, height: 64)
                                .clipShape(RoundedRectangle(cornerRadius: 14.5))
                                .overlay {
                                    RoundedRectangle(cornerRadius: 14.5)
                                        .strokeBorder(
                                            selection == option.iconName ? Color.accentColor : .secondary.opacity(0.25),
                                            lineWidth: selection == option.iconName ? 3 : 1
                                        )
                                }
                            Text(option.label)
                                .font(.caption2)
                                .foregroundStyle(selection == option.iconName ? Color.accentColor : .secondary)
                        }
                    }
                    .buttonStyle(.plain)
                }
            }
            .padding(.vertical, 4)
        }
        .alert("Couldn't change icon", isPresented: Binding(
            get: { errorMessage != nil },
            set: { if !$0 { errorMessage = nil } }
        )) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(errorMessage ?? "")
        }
    }

    private func select(_ option: IconOption) {
        guard option.iconName != selection else { return }
        UIApplication.shared.setAlternateIconName(option.iconName) { error in
            Task { @MainActor in
                if let error {
                    errorMessage = error.localizedDescription
                } else {
                    selection = option.iconName
                }
            }
        }
    }
}
